### PR TITLE
Add [@bs] callsite example

### PR DESCRIPTION
**Pull request by yawaramin**
Show example of using `[@bs]` explicit uncurrying at callsite and show
the error that results from not using the annotation.

### CODE REVIEW

**Comment by bobzhang** [comment]
Is that error from Merlin? Bsb should give a better one

**Comment by yawaramin** [comment]
@bobzhang I'll check, this is what I'm getting from https://reasonml.github.io/try/?reason=DYUwLgBAhgJjBMEC8EDaABARgZwLoQAoAPAGggE8BKZAPgiIgGoKBuAKFEgC9lo54CARjLxKLIA , but I'll check against a downloaded bsb on my machine.

**Comment by chenglou** [comment]
Merlin should also give a good one, since it uses the reason pretty printer which fixes this syntax

**Comment by yawaramin** [comment]
Just checked and latest error message is quite a bit clearer! 'This is an uncurried bucklescript function. It must be applied with `[@bs]`.'

In light of this, this PR doesn't really make sense any more.

**Pull request closed without merging**
