### PR TITLE
Minor logo adjustment + png version for favicon

### PR DESCRIPTION
**Pull request by MoOx**
## Motivation

Currently, BS website doesn't have a favicon on Safari & Chrome (it seems only Firefox support svg for favicon).

screen shot 2018-05-28 at 09 03 40

I would like to see BS icon in here :)

## Work done

- removed temp logo (not actually used)
- renamed svg logo without "_small" as it's SVG (so can be really big ^^)
- tweaked logo just a little (see change below)
- added png version
- use png for favicon instead of svg, hoping it will be better for Safari & Chrome

### Before

before

I found the edge of the B a little to sharp and always see "a bug" in the logo when I look at it

before

### After

after

Minor change with a slightly smaller B.

### CODE REVIEW

**Comment by chenglou** [comment]
Thanks! Though I thought the B was supposed to be sticking out since it's the metal part of the belt?

Btw, here's the source: https://www.dropbox.com/s/y1lwebu3bmw0c9g/BuckleScript%20copy.sketch?dl=0

**Comment by MoOx** [comment]
Thank, I already have the sketch ;)
To be sure, do you want me to rollback the logo change, and just push the png version?

**Comment by MoOx** [comment]
FYI, I forgot it was a belt in the first place. The small version make it looks like a generic "database" logo. Not sure if that's clear enough. Maybe we could adjust the logo to make it clearer in the small version (since large version has never been used yet?)

poke @bloodyowl

**Comment by MoOx** [comment]
What about something like this?


image

**Comment by bobzhang** [comment]
looks great! maybe the background color can still be the old purple?

**Comment by bloodyowl** [comment]
@MoOx looks good 👍

**Comment by MoOx** [comment]
Updated.

screenshot 2018-06-05 at 23 07 08

screenshot 2018-06-05 at 23 07 38

image

**Comment by chenglou** [comment]
Yeah a flatter belt is nice =D

Thanks!

**Comment by chenglou** [comment]
I just realized we had another small logo already!

logo

screenshot 2018-06-05 15 51 33

Which one do you folks like better?

**Comment by MoOx** [comment]
I have seen this one, but were afraid that it look bad in tiny (eg favicon, apple touch icon etc).
Not sure what is better for an icon (as it's more an illustration  - me think)

**Comment by chenglou** [comment]
Yeah makes sense

**Pull request merged**
