### PR TITLE
 Style, grammar, punctuation, spelling, and/or consistency changes.

### PR DESCRIPTION
**Pull request by psb**
Pretty much what the title says. I have not rewritten large parts of the docs, but just little bits here and there. Hopefully, they read and flow a bit better, and the pages are more consistent with each other.

(The 'The Whole JavaScript Ecosystem' to 'The Whole JS Ecosystem' made those grid blocks layout identically at 1280x1440 resolution.)

### CODE REVIEW

**Comment by chenglou** [comment]
Thanks! We'd like to keep the `you're` vs `you are` and others, if possible.

**Comment by psb** [comment]
Sure, I can add those back. Did my changes make the docs too formal?

I would recommend not using 'd contractions or symbols (e.g. +) because they can lead to confusion depending on the context. I think the docs should be as straight forward and unambiguous as possible because the reader is already trying to learn BS/Reason.

**Comment by chenglou** [comment]
Yeah, I'd like the docs to stay casual and light-hearted; reading through docs is already a boring task.

The contractions in most places aren't important and wouldn't cause misunderstanding I think.

**Comment by psb** [comment]
If you agree with guidelines akin to this: https://github.com/hmrc/design-patterns/issues/130, then I'll do something similar to informalize the docs (to keep them casual and lighthearted) while making sure everything is clear.

**Pull request closed without merging**
